/* automatically generated by rust-bindgen 0.72.1 */

pub const __BIONIC__: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __bos_level: u32 = 0;
pub const __ANDROID_API_FUTURE__: u32 = 10000;
pub const __ANDROID_API__: u32 = 10000;
pub const __ANDROID_API_G__: u32 = 9;
pub const __ANDROID_API_I__: u32 = 14;
pub const __ANDROID_API_J__: u32 = 16;
pub const __ANDROID_API_J_MR1__: u32 = 17;
pub const __ANDROID_API_J_MR2__: u32 = 18;
pub const __ANDROID_API_K__: u32 = 19;
pub const __ANDROID_API_L__: u32 = 21;
pub const __ANDROID_API_L_MR1__: u32 = 22;
pub const __ANDROID_API_M__: u32 = 23;
pub const __ANDROID_API_N__: u32 = 24;
pub const __ANDROID_API_N_MR1__: u32 = 25;
pub const __ANDROID_API_O__: u32 = 26;
pub const __ANDROID_API_O_MR1__: u32 = 27;
pub const __ANDROID_API_P__: u32 = 28;
pub const __ANDROID_API_Q__: u32 = 29;
pub const __ANDROID_API_R__: u32 = 30;
pub const __ANDROID_API_S__: u32 = 31;
pub const __ANDROID_API_T__: u32 = 33;
pub const __ANDROID_API_U__: u32 = 34;
pub const __ANDROID_API_V__: u32 = 35;
pub const __ANDROID_NDK__: u32 = 1;
pub const __NDK_MAJOR__: u32 = 28;
pub const __NDK_MINOR__: u32 = 2;
pub const __NDK_BETA__: u32 = 0;
pub const __NDK_BUILD__: u32 = 13676358;
pub const __NDK_CANARY__: u32 = 0;
pub const WCHAR_MIN: u8 = 0u8;
pub const INT8_MIN: i32 = -128;
pub const INT8_MAX: u32 = 127;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST8_MAX: u32 = 127;
pub const UINT8_MAX: u32 = 255;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_FAST8_MAX: u32 = 255;
pub const INT16_MIN: i32 = -32768;
pub const INT16_MAX: u32 = 32767;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const UINT16_MAX: u32 = 65535;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const INT32_MIN: i32 = -2147483648;
pub const INT32_MAX: u32 = 2147483647;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 4294967295;
pub const WINT_MIN: u32 = 0;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Connection {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  An established connection."]
pub type Connection_t = Connection;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SendStream {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  A stream that can only be used to send data"]
pub type SendStream_t = SendStream;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RecvStream {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  A stream that can only be used to receive data."]
pub type RecvStream_t = RecvStream;
pub type wchar_t = ::std::os::raw::c_uint;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
unsafe extern "C" {
    pub fn android_get_device_api_level() -> ::std::os::raw::c_int;
}
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __uintptr_t = ::std::os::raw::c_ulong;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_fast16_t = i64;
pub type uint_fast16_t = u64;
pub type int_fast32_t = i64;
pub type uint_fast32_t = u64;
pub type uintmax_t = u64;
pub type intmax_t = i64;
#[doc = " \\brief\n  Everything is ok"]
pub const EndpointResult_ENDPOINT_RESULT_OK: EndpointResult = 0;
#[doc = " \\brief\n  Failed to bind."]
pub const EndpointResult_ENDPOINT_RESULT_BIND_ERROR: EndpointResult = 1;
#[doc = " \\brief\n  Failed to accept a connection."]
pub const EndpointResult_ENDPOINT_RESULT_ACCEPT_FAILED: EndpointResult = 2;
#[doc = " \\brief\n  Failed to accept a uni directional stream,"]
pub const EndpointResult_ENDPOINT_RESULT_ACCEPT_UNI_FAILED: EndpointResult = 3;
#[doc = " \\brief\n  Failed to accept a bi directional stream,"]
pub const EndpointResult_ENDPOINT_RESULT_ACCEPT_BI_FAILED: EndpointResult = 4;
#[doc = " \\brief\n  Failed to connect and establish a uni directional stream."]
pub const EndpointResult_ENDPOINT_RESULT_CONNECT_UNI_ERROR: EndpointResult = 5;
#[doc = " \\brief\n  Failed to connect and establish a bi directional stream."]
pub const EndpointResult_ENDPOINT_RESULT_CONNECT_BI_ERROR: EndpointResult = 6;
#[doc = " \\brief\n  Failed to connect."]
pub const EndpointResult_ENDPOINT_RESULT_CONNECT_ERROR: EndpointResult = 7;
#[doc = " \\brief\n  Unable to retrive endpoint addr."]
pub const EndpointResult_ENDPOINT_RESULT_ADDR_ERROR: EndpointResult = 8;
#[doc = " \\brief\n  Error while sending data."]
pub const EndpointResult_ENDPOINT_RESULT_SEND_ERROR: EndpointResult = 9;
#[doc = " \\brief\n  Error while reading data."]
pub const EndpointResult_ENDPOINT_RESULT_READ_ERROR: EndpointResult = 10;
#[doc = " \\brief\n  Timeout elapsed."]
pub const EndpointResult_ENDPOINT_RESULT_TIMEOUT: EndpointResult = 11;
#[doc = " \\brief\n  Error while closing."]
pub const EndpointResult_ENDPOINT_RESULT_CLOSE_ERROR: EndpointResult = 12;
#[doc = " \\brief\n  Failed to accept an incoming connection.\n\n  This occurs before the handshake is even attempted.\n\n  Likely not caused by the application or remote. The QUIC connection listens on a normal UDP socket and any reachable network endpoint can send datagrams to it, solicited or not.\n\n  It is common to simply log this error and move on."]
pub const EndpointResult_ENDPOINT_RESULT_INCOMING_ERROR: EndpointResult = 13;
#[doc = " \\brief\n  Unable to find connection for the given `EndpointId`"]
pub const EndpointResult_ENDPOINT_RESULT_CONNECTION_TYPE_ERROR: EndpointResult = 14;
pub type EndpointResult = ::std::os::raw::c_uint;
pub type EndpointResult_t = u8;
unsafe extern "C" {
    #[doc = " \\brief\n  Accept a bi directional stream on this endpoint.\n\n  Blocks the current thread."]
    pub fn connection_accept_bi(
        conn: *const *mut Connection_t,
        send: *mut *mut SendStream_t,
        recv: *mut *mut RecvStream_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Accepts a uni directional stream on this connection.\n\n  Blocks the current thread."]
    pub fn connection_accept_uni(
        conn: *const *mut Connection_t,
        out: *mut *mut RecvStream_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Close a connection\n\n  Consumes the connection, no need to free it afterwards."]
    pub fn connection_close(conn: *mut Connection_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Wait for the connection to be closed.\n\n  Blocks the current thread.\n\n  Consumes the connection, no need to free it afterwards."]
    pub fn connection_closed(conn: *mut Connection_t) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Result must be freed using `connection_free`."]
    pub fn connection_default() -> *mut Connection_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Frees the connection."]
    pub fn connection_free(conn: *mut Connection_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Returns the maximum datagram size. `0` if it is not supported."]
    pub fn connection_max_datagram_size(connection: *const *mut Connection_t) -> usize;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Establish a bi directional connection.\n\n  Blocks the current thread until the connection is established."]
    pub fn connection_open_bi(
        conn: *const *mut Connection_t,
        send: *mut *mut SendStream_t,
        recv: *mut *mut RecvStream_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Establish a uni directional connection.\n\n  Blocks the current thread until the connection is established."]
    pub fn connection_open_uni(
        conn: *const *mut Connection_t,
        out: *mut *mut SendStream_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Returns the ratio of lost packets to sent packets on the selected path.\n  Returns 0.0 if no path is selected or no packets have been sent."]
    pub fn connection_packet_loss(conn: *const *mut Connection_t) -> f64;
}
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vec_uint8 {
    #[doc = " <No documentation available>"]
    pub ptr: *mut u8,
    #[doc = " <No documentation available>"]
    pub len: usize,
    #[doc = " <No documentation available>"]
    pub cap: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Vec_uint8"][::std::mem::size_of::<Vec_uint8>() - 24usize];
    ["Alignment of Vec_uint8"][::std::mem::align_of::<Vec_uint8>() - 8usize];
    ["Offset of field: Vec_uint8::ptr"][::std::mem::offset_of!(Vec_uint8, ptr) - 0usize];
    ["Offset of field: Vec_uint8::len"][::std::mem::offset_of!(Vec_uint8, len) - 8usize];
    ["Offset of field: Vec_uint8::cap"][::std::mem::offset_of!(Vec_uint8, cap) - 16usize];
};
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
pub type Vec_uint8_t = Vec_uint8;
unsafe extern "C" {
    #[doc = " \\brief\n  Reads a datgram.\n\n  Data must not be larger than the available `max_datagram` size.\n\n  Blocks the current thread until a datagram is received."]
    pub fn connection_read_datagram(
        connection: *const *mut Connection_t,
        data: *mut Vec_uint8_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Reads a datgram, with timeout.\n\n  Will block at most `timeout` milliseconds.\n\n  Data received will not be larger than the available `max_datagram` size.\n\n  Blocks the current thread until a datagram is received or the timeout is expired."]
    pub fn connection_read_datagram_timeout(
        connection: *const *mut Connection_t,
        data: *mut Vec_uint8_t,
        timeout_ms: u64,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Estimated roundtrip time for the current connection's selected path in milli seconds.\n  Returns 0 if no path is selected."]
    pub fn connection_rtt(conn: *const *mut Connection_t) -> u64;
}
#[doc = " \\brief\n  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.\n\n  # C layout (for some given type T)\n\n  ```c\n  typedef struct {\n  // Cannot be NULL\n  T * ptr;\n  size_t len;\n  } slice_T;\n  ```\n\n  # Nullable pointer?\n\n  If you want to support the above typedef, but where the `ptr` field is\n  allowed to be `NULL` (with the contents of `len` then being undefined)\n  use the `Option< slice_ptr<_> >` type."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct slice_ref_uint8 {
    #[doc = " \\brief\n  Pointer to the first element (if any)."]
    pub ptr: *const u8,
    #[doc = " \\brief\n  Element count"]
    pub len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of slice_ref_uint8"][::std::mem::size_of::<slice_ref_uint8>() - 16usize];
    ["Alignment of slice_ref_uint8"][::std::mem::align_of::<slice_ref_uint8>() - 8usize];
    ["Offset of field: slice_ref_uint8::ptr"]
        [::std::mem::offset_of!(slice_ref_uint8, ptr) - 0usize];
    ["Offset of field: slice_ref_uint8::len"]
        [::std::mem::offset_of!(slice_ref_uint8, len) - 8usize];
};
#[doc = " \\brief\n  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.\n\n  # C layout (for some given type T)\n\n  ```c\n  typedef struct {\n  // Cannot be NULL\n  T * ptr;\n  size_t len;\n  } slice_T;\n  ```\n\n  # Nullable pointer?\n\n  If you want to support the above typedef, but where the `ptr` field is\n  allowed to be `NULL` (with the contents of `len` then being undefined)\n  use the `Option< slice_ptr<_> >` type."]
pub type slice_ref_uint8_t = slice_ref_uint8;
unsafe extern "C" {
    #[doc = " \\brief\n  Send a single datgram (unreliably).\n\n  Data must not be larger than the available `max_datagram` size."]
    pub fn connection_write_datagram(
        connection: *const *mut Connection_t,
        data: slice_ref_uint8_t,
    ) -> EndpointResult_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Endpoint {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  An endpoint that leverages a quic endpoint, backed by a iroh socket."]
pub type Endpoint_t = Endpoint;
unsafe extern "C" {
    #[doc = " \\brief\n  Accept a new connection on this endpoint.\n\n  Blocks the current thread until a connection is established.\n\n  An [`EndpointResult::IncomingError`] occurring here is likely not caused by the application or remote. The QUIC connection listens on a normal UDP socket and any reachable network endpoint can send datagrams to it, solicited or not.\n  It is not considered fatal and is common to simply log and ignore."]
    pub fn endpoint_accept(
        ep: *const *mut Endpoint_t,
        expected_alpn: slice_ref_uint8_t,
        out: *const *mut Connection_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Accept a new connection on this endpoint.\n\n  Does not prespecify the ALPN, and but rather returns it.\n\n  Blocks the current thread until a connection is established.\n\n  An [`EndpointResult::IncomingError`] occurring here is likely not caused by the application or remote. The QUIC connection listens on a normal UDP socket and any reachable network endpoint can send datagrams to it, solicited or not.\n  It is not considered fatal and is common to simply log and ignore."]
    pub fn endpoint_accept_any(
        ep: *const *mut Endpoint_t,
        alpn_out: *mut Vec_uint8_t,
        out: *const *mut Connection_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Accept a new connection on this endpoint.\n\n  Does not prespecify the ALPN, and but rather returns it.\n\n  Does not block, the provided callback will be called the next time a new connection is accepted or\n  when an error occurs.\n  `ctx` is passed along to the callback, to allow passing context, it must be thread safe as the callback is\n  called from another thread.\n\n  An [`EndpointResult::IncomingError`] occurring here is likely not caused by the application or remote. The QUIC connection listens on a normal UDP socket and any reachable network endpoint can send datagrams to it, solicited or not.\n  It is not considered fatal and is common to simply log and ignore."]
    pub fn endpoint_accept_any_cb(
        ep: *mut Endpoint_t,
        ctx: *const ::std::os::raw::c_void,
        cb: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const ::std::os::raw::c_void,
                arg2: EndpointResult_t,
                arg3: Vec_uint8_t,
                arg4: *mut Connection_t,
            ),
        >,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint8_32_array_t {
    pub idx: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of uint8_32_array_t"][::std::mem::size_of::<uint8_32_array_t>() - 32usize];
    ["Alignment of uint8_32_array_t"][::std::mem::align_of::<uint8_32_array_t>() - 1usize];
    ["Offset of field: uint8_32_array_t::idx"]
        [::std::mem::offset_of!(uint8_32_array_t, idx) - 0usize];
};
#[doc = " \\brief\n  A public key."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PublicKey {
    #[doc = " <No documentation available>"]
    pub key: uint8_32_array_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PublicKey"][::std::mem::size_of::<PublicKey>() - 32usize];
    ["Alignment of PublicKey"][::std::mem::align_of::<PublicKey>() - 1usize];
    ["Offset of field: PublicKey::key"][::std::mem::offset_of!(PublicKey, key) - 0usize];
};
#[doc = " \\brief\n  A public key."]
pub type PublicKey_t = PublicKey;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Url {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  Represents a valid URL."]
pub type Url_t = Url;
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vec_Url_ptr {
    #[doc = " <No documentation available>"]
    pub ptr: *mut *mut Url_t,
    #[doc = " <No documentation available>"]
    pub len: usize,
    #[doc = " <No documentation available>"]
    pub cap: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Vec_Url_ptr"][::std::mem::size_of::<Vec_Url_ptr>() - 24usize];
    ["Alignment of Vec_Url_ptr"][::std::mem::align_of::<Vec_Url_ptr>() - 8usize];
    ["Offset of field: Vec_Url_ptr::ptr"][::std::mem::offset_of!(Vec_Url_ptr, ptr) - 0usize];
    ["Offset of field: Vec_Url_ptr::len"][::std::mem::offset_of!(Vec_Url_ptr, len) - 8usize];
    ["Offset of field: Vec_Url_ptr::cap"][::std::mem::offset_of!(Vec_Url_ptr, cap) - 16usize];
};
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
pub type Vec_Url_ptr_t = Vec_Url_ptr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SocketAddr {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  Represents an IPv4 or IPv6 address, including a port number."]
pub type SocketAddr_t = SocketAddr;
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vec_SocketAddr_ptr {
    #[doc = " <No documentation available>"]
    pub ptr: *mut *mut SocketAddr_t,
    #[doc = " <No documentation available>"]
    pub len: usize,
    #[doc = " <No documentation available>"]
    pub cap: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Vec_SocketAddr_ptr"][::std::mem::size_of::<Vec_SocketAddr_ptr>() - 24usize];
    ["Alignment of Vec_SocketAddr_ptr"][::std::mem::align_of::<Vec_SocketAddr_ptr>() - 8usize];
    ["Offset of field: Vec_SocketAddr_ptr::ptr"]
        [::std::mem::offset_of!(Vec_SocketAddr_ptr, ptr) - 0usize];
    ["Offset of field: Vec_SocketAddr_ptr::len"]
        [::std::mem::offset_of!(Vec_SocketAddr_ptr, len) - 8usize];
    ["Offset of field: Vec_SocketAddr_ptr::cap"]
        [::std::mem::offset_of!(Vec_SocketAddr_ptr, cap) - 16usize];
};
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
pub type Vec_SocketAddr_ptr_t = Vec_SocketAddr_ptr;
#[doc = " \\brief\n  A peer and it's addressing information."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct EndpointAddr {
    #[doc = " \\brief\n  The endpoint's public key."]
    pub id: PublicKey_t,
    #[doc = " \\brief\n  The peers relay urls."]
    pub relay_urls: Vec_Url_ptr_t,
    #[doc = " \\brief\n  The peers IP addresses"]
    pub ip_addrs: Vec_SocketAddr_ptr_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of EndpointAddr"][::std::mem::size_of::<EndpointAddr>() - 80usize];
    ["Alignment of EndpointAddr"][::std::mem::align_of::<EndpointAddr>() - 8usize];
    ["Offset of field: EndpointAddr::id"][::std::mem::offset_of!(EndpointAddr, id) - 0usize];
    ["Offset of field: EndpointAddr::relay_urls"]
        [::std::mem::offset_of!(EndpointAddr, relay_urls) - 32usize];
    ["Offset of field: EndpointAddr::ip_addrs"]
        [::std::mem::offset_of!(EndpointAddr, ip_addrs) - 56usize];
};
#[doc = " \\brief\n  A peer and it's addressing information."]
pub type EndpointAddr_t = EndpointAddr;
unsafe extern "C" {
    #[doc = " \\brief\n  Get the endpoint dialing information of this iroh endpoint."]
    pub fn endpoint_addr(ep: *const *mut Endpoint_t, out: *mut EndpointAddr_t) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Add the given direct addresses to the peer's addr info."]
    pub fn endpoint_addr_add_ip_addrs(
        endpoint_addr: *mut EndpointAddr_t,
        address: *mut SocketAddr_t,
    );
}
unsafe extern "C" {
    #[doc = " \\brief\n  Add a relay url to the peer's addr info."]
    pub fn endpoint_addr_add_relay_url(addr: *mut EndpointAddr_t, relay_url: *mut Url_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Formats the given endpoint addr as a string.\n\n  Result must be freed with `rust_free_string`"]
    pub fn endpoint_addr_as_str(addr: *const EndpointAddr_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Create a an empty (invalid) addr with no details.\n\n  Must be freed using `endpoint_addr_free`."]
    pub fn endpoint_addr_default() -> EndpointAddr_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Free the endpoint addr."]
    pub fn endpoint_addr_free(endpoint_addr: EndpointAddr_t);
}
#[doc = " \\brief\n  Everything is ok."]
pub const AddrResult_ADDR_RESULT_OK: AddrResult = 0;
#[doc = " \\brief\n  Url was invalid."]
pub const AddrResult_ADDR_RESULT_INVALID_URL: AddrResult = 1;
#[doc = " \\brief\n  SocketAddr was invalid."]
pub const AddrResult_ADDR_RESULT_INVALID_SOCKET_ADDR: AddrResult = 2;
#[doc = " \\brief\n  The endpoint addr was invalid."]
pub const AddrResult_ADDR_RESULT_INVALID_ENDPOINT_ADDR: AddrResult = 3;
pub type AddrResult = ::std::os::raw::c_uint;
pub type AddrResult_t = u8;
unsafe extern "C" {
    #[doc = " \\brief\n  Parses the full endpoint addr string representation."]
    pub fn endpoint_addr_from_string(
        input: *const ::std::os::raw::c_char,
        out: *mut EndpointAddr_t,
    ) -> AddrResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Get the nth direct addresses of this peer."]
    pub fn endpoint_addr_ip_addrs_nth(addr: *const EndpointAddr_t, i: usize)
    -> *const SocketAddr_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Create a new addr with no details.\n\n  Must be freed using `endpoint_addr_free`."]
    pub fn endpoint_addr_new(id: PublicKey_t) -> EndpointAddr_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Get the relay url of this peer."]
    pub fn endpoint_addr_relay_urls_nth(addr: *const EndpointAddr_t, i: usize)
    -> *const *mut Url_t;
}
#[doc = " \\brief\n  Relay mode is entirely disabled"]
pub const RelayMode_RELAY_MODE_DISABLED: RelayMode = 0;
#[doc = " \\brief\n  Default relay map is used."]
pub const RelayMode_RELAY_MODE_DEFAULT: RelayMode = 1;
pub type RelayMode = ::std::os::raw::c_uint;
pub type RelayMode_t = u8;
#[doc = " \\brief\n  Use no discovery mechanism. The default."]
pub const DiscoveryConfig_DISCOVERY_CONFIG_NONE: DiscoveryConfig = 0;
#[doc = " \\brief\n  DNS Discovery service.\n\n  Allows for global endpoint discovery. Requires access to the internet to work properly."]
pub const DiscoveryConfig_DISCOVERY_CONFIG_D_N_S: DiscoveryConfig = 1;
#[doc = " \\brief\n  Mdns Discovery service.\n\n  Allows for local endpoint discovery. Discovers other iroh endpoints in your local network\n  If your local network does not have multicast abilities, creating a local swarm discovery service will log an error, but fail silently."]
pub const DiscoveryConfig_DISCOVERY_CONFIG_MDNS: DiscoveryConfig = 2;
#[doc = " \\brief\n  Use both DNS and Mdns Discovery\n  If your local network does not have multicast abilities, creating a local swarm discovery service will log an error, but fail silently."]
pub const DiscoveryConfig_DISCOVERY_CONFIG_ALL: DiscoveryConfig = 3;
pub type DiscoveryConfig = ::std::os::raw::c_uint;
pub type DiscoveryConfig_t = u8;
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vec_Vec_uint8 {
    #[doc = " <No documentation available>"]
    pub ptr: *mut Vec_uint8_t,
    #[doc = " <No documentation available>"]
    pub len: usize,
    #[doc = " <No documentation available>"]
    pub cap: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Vec_Vec_uint8"][::std::mem::size_of::<Vec_Vec_uint8>() - 24usize];
    ["Alignment of Vec_Vec_uint8"][::std::mem::align_of::<Vec_Vec_uint8>() - 8usize];
    ["Offset of field: Vec_Vec_uint8::ptr"][::std::mem::offset_of!(Vec_Vec_uint8, ptr) - 0usize];
    ["Offset of field: Vec_Vec_uint8::len"][::std::mem::offset_of!(Vec_Vec_uint8, len) - 8usize];
    ["Offset of field: Vec_Vec_uint8::cap"][::std::mem::offset_of!(Vec_Vec_uint8, cap) - 16usize];
};
#[doc = " \\brief\n  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout"]
pub type Vec_Vec_uint8_t = Vec_Vec_uint8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SecretKey {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  A secret key."]
pub type SecretKey_t = SecretKey;
#[doc = " \\brief\n  Configuration options for the Endpoint."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct EndpointConfig {
    #[doc = " <No documentation available>"]
    pub relay_mode: RelayMode_t,
    #[doc = " <No documentation available>"]
    pub discovery_cfg: DiscoveryConfig_t,
    #[doc = " <No documentation available>"]
    pub alpn_protocols: Vec_Vec_uint8_t,
    #[doc = " <No documentation available>"]
    pub secret_key: *mut SecretKey_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of EndpointConfig"][::std::mem::size_of::<EndpointConfig>() - 40usize];
    ["Alignment of EndpointConfig"][::std::mem::align_of::<EndpointConfig>() - 8usize];
    ["Offset of field: EndpointConfig::relay_mode"]
        [::std::mem::offset_of!(EndpointConfig, relay_mode) - 0usize];
    ["Offset of field: EndpointConfig::discovery_cfg"]
        [::std::mem::offset_of!(EndpointConfig, discovery_cfg) - 1usize];
    ["Offset of field: EndpointConfig::alpn_protocols"]
        [::std::mem::offset_of!(EndpointConfig, alpn_protocols) - 8usize];
    ["Offset of field: EndpointConfig::secret_key"]
        [::std::mem::offset_of!(EndpointConfig, secret_key) - 32usize];
};
#[doc = " \\brief\n  Configuration options for the Endpoint."]
pub type EndpointConfig_t = EndpointConfig;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SocketAddrV4 {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  Represents an IPv4 address, including a port number."]
pub type SocketAddrV4_t = SocketAddrV4;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SocketAddrV6 {
    _unused: [u8; 0],
}
#[doc = " \\brief\n  Represents an IPv6 address, including a port number."]
pub type SocketAddrV6_t = SocketAddrV6;
unsafe extern "C" {
    #[doc = " \\brief\n  Attempts to bind the endpoint to the provided IPv4 and IPv6 address.\n\n  If the selected port is already in use, a random port will be used.\n\n  Blocks the current thread."]
    pub fn endpoint_bind(
        config: *const EndpointConfig_t,
        ipv4_addr: *mut SocketAddrV4_t,
        ipv6_addr: *mut SocketAddrV6_t,
        out: *const *mut Endpoint_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Closes the endpoint.\n\n  It blocks all incoming connections and then waits for all current connections\n  to close gracefully, before shutting down the endpoint.\n\n  Consumes the endpoint, no need to free it afterwards."]
    pub fn endpoint_close(ep: *mut Endpoint_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Add the given ALPN to the list of accepted ALPNs."]
    pub fn endpoint_config_add_alpn(config: *mut EndpointConfig_t, alpn: slice_ref_uint8_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Sets the given secret key to use."]
    pub fn endpoint_config_add_secret_key(
        config: *mut EndpointConfig_t,
        secret_key: *mut SecretKey_t,
    );
}
unsafe extern "C" {
    #[doc = " \\brief\n  Generate a default endpoint configuration.\n\n  Must be freed using `endpoint_config_free`."]
    pub fn endpoint_config_default() -> EndpointConfig_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Frees the iroh endpoint config."]
    pub fn endpoint_config_free(config: EndpointConfig_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Connects to the given endpoint.\n\n  Blocks until the connection is established."]
    pub fn endpoint_connect(
        ep: *const *mut Endpoint_t,
        alpn: slice_ref_uint8_t,
        endpoint_addr: EndpointAddr_t,
        out: *const *mut Connection_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Generate a default endpoint.\n\n  Must be freed using `endpoint_free`."]
    pub fn endpoint_default() -> *mut Endpoint_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Frees the iroh endpoint."]
    pub fn endpoint_free(ep: *mut Endpoint_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Let the endpoint know that the underlying network conditions might have changed.\n\n  This really only needs to be called on android,\n  Ref https://developer.android.com/training/monitoring-device-state/connectivity-status-type"]
    pub fn endpoint_network_change(ep: *const *mut Endpoint_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Returns once the endpoint is online.\n\n  We are considered online if we have a home relay and at least one\n  direct address.\n\n  Will block at most `timeout` milliseconds."]
    pub fn endpoint_online(ep: *const *mut Endpoint_t, timeout_ms: u64) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Enables tracing for iroh.\n\n  Log level can be controlled using the env variable `IROH_C_LOG`."]
    pub fn iroh_enable_tracing();
}
unsafe extern "C" {
    #[doc = " \\brief\n  Returns the public key as a base32 string.\n\n  Result must be freed using `rust_free_string`"]
    pub fn public_key_as_base32(key: *const PublicKey_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Generate a default (invalid) public key.\n\n  Result must be freed using `public_key_free`."]
    pub fn public_key_default() -> PublicKey_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Free the passed in key."]
    pub fn public_key_free(_key: PublicKey_t);
}
#[doc = " \\brief\n  Everything is ok."]
pub const KeyResult_KEY_RESULT_OK: KeyResult = 0;
#[doc = " \\brief\n  Invalid public key material."]
pub const KeyResult_KEY_RESULT_INVALID_PUBLIC_KEY: KeyResult = 1;
#[doc = " \\brief\n  Invalid secret key material."]
pub const KeyResult_KEY_RESULT_INVALID_SECRET_KEY: KeyResult = 2;
pub type KeyResult = ::std::os::raw::c_uint;
pub type KeyResult_t = u8;
unsafe extern "C" {
    #[doc = " \\brief\n  Parses the public key from a base32 string."]
    pub fn public_key_from_base32(
        raw_key: *const ::std::os::raw::c_char,
        out: *mut PublicKey_t,
    ) -> KeyResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Must be freed using `recv_stream_free`."]
    pub fn recv_stream_default() -> *mut RecvStream_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Free the recv stream.\n\n  Implicitly calls `stop(0)` on the connection.\n\n  Must be called before `endpoint_free`"]
    pub fn recv_stream_free(stream: *mut RecvStream_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Unique stream id."]
    pub fn recv_stream_id(stream: *const *mut RecvStream_t) -> u64;
}
#[doc = " \\brief\n  `&'lt mut [T]` but with a guaranteed `#[repr(C)]` layout.\n\n  # C layout (for some given type T)\n\n  ```c\n  typedef struct {\n  // Cannot be NULL\n  T * ptr;\n  size_t len;\n  } slice_T;\n  ```\n\n  # Nullable pointer?\n\n  If you want to support the above typedef, but where the `ptr` field is\n  allowed to be `NULL` (with the contents of `len` then being undefined)\n  use the `Option< slice_ptr<_> >` type."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct slice_mut_uint8 {
    #[doc = " \\brief\n  Pointer to the first element (if any)."]
    pub ptr: *mut u8,
    #[doc = " \\brief\n  Element count"]
    pub len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of slice_mut_uint8"][::std::mem::size_of::<slice_mut_uint8>() - 16usize];
    ["Alignment of slice_mut_uint8"][::std::mem::align_of::<slice_mut_uint8>() - 8usize];
    ["Offset of field: slice_mut_uint8::ptr"]
        [::std::mem::offset_of!(slice_mut_uint8, ptr) - 0usize];
    ["Offset of field: slice_mut_uint8::len"]
        [::std::mem::offset_of!(slice_mut_uint8, len) - 8usize];
};
#[doc = " \\brief\n  `&'lt mut [T]` but with a guaranteed `#[repr(C)]` layout.\n\n  # C layout (for some given type T)\n\n  ```c\n  typedef struct {\n  // Cannot be NULL\n  T * ptr;\n  size_t len;\n  } slice_T;\n  ```\n\n  # Nullable pointer?\n\n  If you want to support the above typedef, but where the `ptr` field is\n  allowed to be `NULL` (with the contents of `len` then being undefined)\n  use the `Option< slice_ptr<_> >` type."]
pub type slice_mut_uint8_t = slice_mut_uint8;
unsafe extern "C" {
    #[doc = " \\brief\n  Receive data on this stream.\n\n  Blocks the current thread.\n\n  Returns how many bytes were read. Returns `-1` if an error occured."]
    pub fn recv_stream_read(stream: *mut *mut RecvStream_t, data: slice_mut_uint8_t) -> i64;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Receive data on this stream and return with an error if reading exceeds the\n  given timeout.\n\n  Blocks the current thread.\n\n  On success, returns how many bytes were read in the `bytes_read` parameter."]
    pub fn recv_stream_read_timeout(
        stream: *mut *mut RecvStream_t,
        data: slice_mut_uint8_t,
        timeout_ms: u64,
    ) -> i64;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Receive data on this stream.\n\n  Size limit specifies how much data at most is read.\n\n  Blocks the current thread, until either the full stream has been read, or\n  the timeout has expired."]
    pub fn recv_stream_read_to_end_timeout(
        stream: *mut *mut RecvStream_t,
        data: *mut Vec_uint8_t,
        size_limit: usize,
        timeout_ms: u64,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Allocates a buffer managed by rust, given the initial size."]
    pub fn rust_buffer_alloc(size: usize) -> Vec_uint8_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Frees the rust buffer."]
    pub fn rust_buffer_free(buf: Vec_uint8_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Returns the length of the buffer."]
    pub fn rust_buffer_len(buf: *const Vec_uint8_t) -> usize;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Frees a Rust-allocated string."]
    pub fn rust_free_string(string: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Returns the secret key as a base32 string.\n\n  Result must be freed using `rust_free_string`"]
    pub fn secret_key_as_base32(key: *const SecretKey_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Generate a default secret key.\n\n  Result must be freed using `secret_key_free`."]
    pub fn secret_key_default() -> *mut SecretKey_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Free the passed in key."]
    pub fn secret_key_free(key: *mut SecretKey_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Parses the secret key from a base32 string."]
    pub fn secret_key_from_base32(
        raw_key: *const ::std::os::raw::c_char,
        out: *mut *mut SecretKey_t,
    ) -> KeyResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Generates a new key with default OS randomness.\n\n  Result must be freed using `secret_key_free`"]
    pub fn secret_key_generate() -> *mut SecretKey_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  The public key for this secret key.\n\n  Result must be freed using `public_key_free`"]
    pub fn secret_key_public(key: *const SecretKey_t) -> PublicKey_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Must be freed using `send_stream_free`."]
    pub fn send_stream_default() -> *mut SendStream_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Finish the sending on this stream.\n\n  Consumes the send stream, no need to free it afterwards."]
    pub fn send_stream_finish(stream: *mut SendStream_t) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Frees the send stream.\n\n  Must be called before `endpoint_free`"]
    pub fn send_stream_free(stream: *mut SendStream_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Unique stream id."]
    pub fn send_stream_id(stream: *const *mut SendStream_t) -> u64;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Send data on the stream.\n\n  Blocks the current thread."]
    pub fn send_stream_write(
        stream: *mut *mut SendStream_t,
        data: slice_ref_uint8_t,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Send data on the stream, returning an error if the data was not written\n  before the given timeout.\n\n  Blocks the current thread."]
    pub fn send_stream_write_timeout(
        stream: *mut *mut SendStream_t,
        data: slice_ref_uint8_t,
        timeout_ms: u64,
    ) -> EndpointResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Formats the given socket addr as a string\n\n  Result must be freed with `rust_free_string`"]
    pub fn socket_addr_as_str(addr: *const SocketAddr_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " <No documentation available>"]
    pub fn socket_addr_default() -> *mut SocketAddr_t;
}
unsafe extern "C" {
    #[doc = " <No documentation available>"]
    pub fn socket_addr_free(addr: *mut SocketAddr_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Try to parse a url from a string."]
    pub fn socket_addr_from_string(
        input: *const ::std::os::raw::c_char,
        out: *mut *mut SocketAddr_t,
    ) -> AddrResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Formats the given socket addr as a string\n\n  Result must be freed with `rust_free_string`"]
    pub fn socket_addr_v4_as_str(addr: *const SocketAddrV4_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " <No documentation available>"]
    pub fn socket_addr_v4_default() -> *mut SocketAddrV4_t;
}
unsafe extern "C" {
    #[doc = " <No documentation available>"]
    pub fn socket_addr_v4_free(addr: *mut SocketAddrV4_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Try to parse a url from a string."]
    pub fn socket_addr_v4_from_string(
        input: *const ::std::os::raw::c_char,
        out: *mut *mut SocketAddrV4_t,
    ) -> AddrResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Formats the given socket addr as a string\n\n  Result must be freed with `rust_free_string`"]
    pub fn socket_addr_v6_as_str(addr: *const SocketAddrV6_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " <No documentation available>"]
    pub fn socket_addr_v6_default() -> *mut SocketAddrV6_t;
}
unsafe extern "C" {
    #[doc = " <No documentation available>"]
    pub fn socket_addr_v6_free(addr: *mut SocketAddrV6_t);
}
unsafe extern "C" {
    #[doc = " \\brief\n  Try to parse a url from a string."]
    pub fn socket_addr_v6_from_string(
        input: *const ::std::os::raw::c_char,
        out: *mut *mut SocketAddrV6_t,
    ) -> AddrResult_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Formats the given url as a string\n\n  Result must be freed with `rust_free_string`"]
    pub fn url_as_str(url: *const Url_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Creates an initialized but invalid Url."]
    pub fn url_default() -> *mut Url_t;
}
unsafe extern "C" {
    #[doc = " \\brief\n  Try to parse a url from a string."]
    pub fn url_from_string(
        input: *const ::std::os::raw::c_char,
        out: *mut *mut Url_t,
    ) -> AddrResult_t;
}
