<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>N0.IrohNet.NativeAssets.Win32</PackageId>
		<Company>N0 Inc.</Company>
		<Description>C# .NET bindings for the Iroh library</Description>
		<PackageTags>iroh;networking;bindings;native</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/IsaMorphic/N0.IrohNet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="runtimes/**" />
		<EmbeddedResource Remove="runtimes/**" />
		<None Remove="runtimes/**" />
	</ItemGroup>

	<PropertyGroup>
		<RustTargetTriple Condition="'$(RuntimeIdentifier)' == 'win-x64'">x86_64-pc-windows-msvc</RustTargetTriple>
		<RustTargetTriple Condition="'$(RuntimeIdentifier)' == 'win-arm64'">aarch64-pc-windows-msvc</RustTargetTriple>
		<RustLibraryFileName Condition="'$(RuntimeIdentifier)' == 'win-x64'">iroh_bindgen.dll</RustLibraryFileName>
		<RustLibraryFileName Condition="'$(RuntimeIdentifier)' == 'win-arm64'">iroh_bindgen.dll</RustLibraryFileName>
	</PropertyGroup>

	<ItemGroup>
		<RustTargetOutput Include="../iroh-bindgen/target/$(RustTargetTriple)/release/$(RustLibraryFileName)" />
		<NativeLibs Include="runtimes/**" />
		<None Include="@(NativeLibs)" PackagePath="runtimes/">
			<Pack>true</Pack>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MinVer" Version="7.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<Target Condition="'$(RuntimeIdentifier)' != ''" Name="rustc" BeforeTargets="PreBuildEvent">
		<Exec WorkingDirectory="../iroh-bindgen" Command="rustup target install $(RustTargetTriple)" />
		
		<Exec WorkingDirectory="../iroh-bindgen" Command="cargo build --target $(RustTargetTriple) --profile release" />

		<Copy SourceFiles="@(RustTargetOutput)" DestinationFolder="runtimes/$(RuntimeIdentifier)/native" />
	</Target>
</Project>